### ISSUE TITLE
zinbwave-DESeq2 issue

### ISSUE THREAD

**Issue by sqsun** [statOmics/zinbwaveZinger#3]
I am failing to fit the zinbwave-DESeq2 model following the code (the example data you provided), with the error message below:
>dse <- DESeq2::estimateDispersions(dse)
gene-wise dispersion estimates
Error in getAndCheckWeights(object, modelMatrix) : 
  all(weights.ok) is not TRUE

**Comment by koenvandenberge** [comment]
This should be resolved by updating zinbwave and re-running the code. See the following issue: https://github.com/drisso/zinbwave/issues/33
